/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.pi.basepi.VIEW;

import javax.swing.JOptionPane;
import projeto.pi.basepi.DAO.ProdutoDAO;
import projeto.pi.basepi.MODELS.Produto;

/**
 *
 * @author athyla
 */
public class AtualizarProduto extends javax.swing.JFrame {

    Produto objAlterar = null;

    /**
     * Creates new form CadastroProduto
     */
    public AtualizarProduto() {
        initComponents();
    }

    public AtualizarProduto(Produto produto) {
        initComponents();

        this.objAlterar = produto;
        txtApNome.setText(String.valueOf((objAlterar.getNome())));
        txtApMarca.setText(String.valueOf(objAlterar.getMarca()));
        txtApEstoque.setText(String.valueOf(objAlterar.getQntd()));
        txtApPreco.setText(String.valueOf(objAlterar.getPreco()));
        txtAdpDesc.setText(String.valueOf(objAlterar.getDescricao()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlAtualizarProduto = new javax.swing.JPanel();
        lblAtualizarProduto = new javax.swing.JLabel();
        lblApMarca = new javax.swing.JLabel();
        txtApMarca = new javax.swing.JTextField();
        lblApNome = new javax.swing.JLabel();
        lblApEstoque = new javax.swing.JLabel();
        lblApPreco = new javax.swing.JLabel();
        txtApNome = new javax.swing.JTextField();
        txtApEstoque = new javax.swing.JTextField();
        txtApPreco = new javax.swing.JFormattedTextField();
        lblApDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAdpDesc = new javax.swing.JTextArea();
        btnApCancelar = new javax.swing.JButton();
        btnApCadastrar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAtualizarProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAtualizarProduto.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblAtualizarProduto.setText("Atualizar Produto");

        javax.swing.GroupLayout pnlAtualizarProdutoLayout = new javax.swing.GroupLayout(pnlAtualizarProduto);
        pnlAtualizarProduto.setLayout(pnlAtualizarProdutoLayout);
        pnlAtualizarProdutoLayout.setHorizontalGroup(
            pnlAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );
        pnlAtualizarProdutoLayout.setVerticalGroup(
            pnlAtualizarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtualizarProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAtualizarProduto)
                .addContainerGap())
        );

        lblApMarca.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApMarca.setText("Marca:");

        lblApNome.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApNome.setText("Nome:");

        lblApEstoque.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApEstoque.setText("Qtd Estoque");

        lblApPreco.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApPreco.setText("Preço:");

        txtApPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtApPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApPrecoActionPerformed(evt);
            }
        });

        lblApDesc.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApDesc.setText("Descrição:");

        txtAdpDesc.setColumns(20);
        txtAdpDesc.setRows(5);
        jScrollPane2.setViewportView(txtAdpDesc);

        btnApCancelar.setText("Cancelar");
        btnApCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApCancelarActionPerformed(evt);
            }
        });

        btnApCadastrar.setText("Atualizar");
        btnApCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblApPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApPreco))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblApEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtApEstoque))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblApNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApNome))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblApMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblApDesc)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnApCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnApCadastrar))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApMarca)
                    .addComponent(txtApMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApNome)
                    .addComponent(txtApNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApEstoque)
                    .addComponent(txtApEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApPreco)
                    .addComponent(txtApPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApCadastrar)
                    .addComponent(btnApCancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApPrecoActionPerformed

    private void btnApCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnApCancelarActionPerformed

    private void btnApCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApCadastrarActionPerformed
        String texto = txtApMarca.getText();

        int idMarca = 0;

        if (texto.equals("amd") || texto.equals("AMD")) {
            idMarca = 1;
        } else if (texto.equals("INTEL") || texto.equals("intel")) {
            idMarca = 2;
        } else if (texto.equals("corsair") || texto.equals("CORSAIR")) {
            idMarca = 3;
        } else if (texto.equals("gigabyte") || texto.equals("GIGABYTE")) {
            idMarca = 4;
        } else if (texto.equals("ASROCK    ") || texto.equals("asrock")) {
            idMarca = 5;
        } else if (texto.equals("MSI    ") || texto.equals("msi")) {
            idMarca = 6;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nao temos essa marca por favor inserir outra");
        }

        String nome = txtApNome.getText().toUpperCase();
        String desc = txtAdpDesc.getText();

        String numero = txtApPreco.getText();
        numero = numero.replace(",", ".");

        double preco = Double.parseDouble(numero);
        int qtd = Integer.parseInt(txtApEstoque.getText());

        objAlterar.setMarca(idMarca);
        objAlterar.setNome(nome);
        objAlterar.setDescricao(desc);
        objAlterar.setPreco(preco);
        objAlterar.setQntd(qtd);

        boolean retorno = ProdutoDAO.alterar(objAlterar);

        if (retorno) {
            JOptionPane.showMessageDialog(rootPane, "Sucesso");
            this.dispose();
        }
    }//GEN-LAST:event_btnApCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApCadastrar;
    private javax.swing.JButton btnApCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblApDesc;
    private javax.swing.JLabel lblApEstoque;
    private javax.swing.JLabel lblApMarca;
    private javax.swing.JLabel lblApNome;
    private javax.swing.JLabel lblApPreco;
    private javax.swing.JLabel lblAtualizarProduto;
    private javax.swing.JPanel pnlAtualizarProduto;
    private javax.swing.JTextArea txtAdpDesc;
    private javax.swing.JTextField txtApEstoque;
    private javax.swing.JTextField txtApMarca;
    private javax.swing.JTextField txtApNome;
    private javax.swing.JFormattedTextField txtApPreco;
    // End of variables declaration//GEN-END:variables
}
