/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.pi.basepi.VIEW;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import projeto.pi.basepi.DAO.ClienteDAO;
import projeto.pi.basepi.MODELS.Cliente;
import projeto.pi.basepi.MODELS.Endereco;

/**
 *
 * @author Athyla
 */
public class AtualizarCliente extends javax.swing.JFrame {
    Cliente clienteCarregado = null;
    Endereco enderecoCarregado = null;
    /**
     * Creates new form CadastroCliente
     */
    public AtualizarCliente() {
        initComponents();
    }
    
   public AtualizarCliente(Cliente cliente, Endereco endereco) {
        initComponents();
        clienteCarregado = cliente;
        enderecoCarregado = endereco;
        txtAcNome.setText(cliente.getNome()); 
        txtAcEmail.setText(cliente.getEmail());       
        txtCdcCpf.setText(cliente.getCPF());   
        SimpleDateFormat dtBrasil = new SimpleDateFormat("dd/MM/yyyy");
        
        txtAcDtNascimento.setText(dtBrasil.format(cliente.getDataNascimento()));
        
        if(cliente.getGenero().equalsIgnoreCase("Masculino")){
            cboAcGenero.setSelectedIndex(0);
        }
        else if(cliente.getGenero().equalsIgnoreCase("Feminino")){
            cboAcGenero.setSelectedIndex(1);
        }
        else{
            cboAcGenero.setSelectedIndex(2);
            
        }
        
        txtAcLogradouro.setText(endereco.getLogradouro());
        
        txtAcNumero.setText(endereco.getNumero());
        
        txtAcCep.setText(endereco.getCep());
        
        txtAcBairro.setText(endereco.getBairro());
        
        txtAcComplemento.setText(endereco.getComplemento());
        
        txtAcCidade.setText(endereco.getCidade());
        
        cboAcUF.setSelectedItem(endereco.getUf());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblAcNome = new javax.swing.JLabel();
        txtAcNome = new javax.swing.JTextField();
        lblAcEmail = new javax.swing.JLabel();
        txtAcEmail = new javax.swing.JTextField();
        lblAcDtNascimento = new javax.swing.JLabel();
        txtAcDtNascimento = new javax.swing.JFormattedTextField();
        lblAcGenero = new javax.swing.JLabel();
        cboAcGenero = new javax.swing.JComboBox<>();
        lblAcCpf = new javax.swing.JLabel();
        txtCdcCpf = new javax.swing.JFormattedTextField();
        btnAcCancelar = new javax.swing.JButton();
        lblAcTelefone = new javax.swing.JLabel();
        txtAcTelefone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        lblAcLogradouro = new javax.swing.JLabel();
        txtAcLogradouro = new javax.swing.JTextField();
        lblAcNumero = new javax.swing.JLabel();
        txtAcNumero = new javax.swing.JTextField();
        lblAcCep = new javax.swing.JLabel();
        txtAcCep = new javax.swing.JFormattedTextField();
        lblAcBairro = new javax.swing.JLabel();
        txtAcBairro = new javax.swing.JTextField();
        lblAcComplemento = new javax.swing.JLabel();
        txtAcComplemento = new javax.swing.JTextField();
        lblAcCidade = new javax.swing.JLabel();
        txtAcCidade = new javax.swing.JTextField();
        lblAcUf = new javax.swing.JLabel();
        cboAcUF = new javax.swing.JComboBox<>();
        btnAcAtualizar = new javax.swing.JButton();
        pnlAc = new javax.swing.JPanel();
        lblAc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAcNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcNome.setText("Nome*:");

        lblAcEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcEmail.setText("E-mail*:");

        lblAcDtNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcDtNascimento.setText("Data de Nascimento*:");

        try {
            txtAcDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAcGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcGenero.setText("Gênero*:");

        cboAcGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Transgênero" }));
        cboAcGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAcGeneroActionPerformed(evt);
            }
        });

        lblAcCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcCpf.setText("CPF*:");

        try {
            txtCdcCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAcCancelar.setText("Cancelar");
        btnAcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcCancelarActionPerformed(evt);
            }
        });

        lblAcTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcTelefone.setText("Telefone*:");

        try {
            txtAcTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAcNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAcNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAcTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAcTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAcCancelar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAcDtNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAcDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboAcGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAcEmail)
                            .addComponent(lblAcCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCdcCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcNome)
                    .addComponent(txtAcNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcEmail)
                    .addComponent(txtAcEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcCpf)
                    .addComponent(txtCdcCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcDtNascimento)
                    .addComponent(txtAcDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAcGenero)
                    .addComponent(cboAcGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcTelefone)
                    .addComponent(txtAcTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnAcCancelar)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        lblAcLogradouro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcLogradouro.setText("Logradouro*:");

        lblAcNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcNumero.setText("Número*:");

        lblAcCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcCep.setText("CEP*:");

        try {
            txtAcCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAcBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcBairro.setText("Bairro*:");

        lblAcComplemento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcComplemento.setText("Complemento:");

        lblAcCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcCidade.setText("Cidade*:");

        lblAcUf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcUf.setText("UF*:");

        cboAcUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "TO", " " }));
        cboAcUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAcUFActionPerformed(evt);
            }
        });

        btnAcAtualizar.setText("Atualizar Dados");
        btnAcAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAcCidade)
                                .addGap(18, 18, 18)
                                .addComponent(txtAcCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAcUf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboAcUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAcLogradouro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAcLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAcNumero)
                                    .addComponent(lblAcBairro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtAcNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAcCep)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAcCep, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAcBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAcComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAcComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAcAtualizar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcLogradouro)
                    .addComponent(txtAcLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcNumero)
                    .addComponent(txtAcNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAcCep)
                    .addComponent(txtAcCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcBairro)
                    .addComponent(txtAcBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcComplemento)
                    .addComponent(txtAcComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcCidade)
                    .addComponent(txtAcCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAcUf)
                    .addComponent(cboAcUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAcAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        pnlAc.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAc.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblAc.setText("Atualizar Cliente");

        javax.swing.GroupLayout pnlAcLayout = new javax.swing.GroupLayout(pnlAc);
        pnlAc.setLayout(pnlAcLayout);
        pnlAcLayout.setHorizontalGroup(
            pnlAcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );
        pnlAcLayout.setVerticalGroup(
            pnlAcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAc)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(pnlAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboAcUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAcUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAcUFActionPerformed

    private void cboAcGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAcGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAcGeneroActionPerformed

    private void btnAcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcCancelarActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_btnAcCancelarActionPerformed

    private void btnAcAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcAtualizarActionPerformed
      if(txtAcNome.getText().equalsIgnoreCase("") ||txtAcDtNascimento.getText().equalsIgnoreCase("") || txtAcLogradouro.getText().equalsIgnoreCase("") || txtAcEmail.getText().equalsIgnoreCase("") || txtCdcCpf.getText().equalsIgnoreCase("") || txtAcCidade.getText().equalsIgnoreCase("") || txtAcComplemento.getText().equalsIgnoreCase("") || 
                txtAcCep.getText().equalsIgnoreCase("") || txtAcBairro.getText().equalsIgnoreCase("") || txtAcTelefone.getText().equalsIgnoreCase("") ){
            JOptionPane.showMessageDialog(rootPane, "Preencha Todos os Campos!!");
           
        }else{
            
             String nome = txtAcNome.getText().toUpperCase();
             String email = txtAcEmail.getText().toUpperCase();
             String cpf = txtCdcCpf.getText();
             String dataBr = txtAcDtNascimento.getText();
             Date dtEua = TraduzirData(dataBr);
             String sexo = (String) cboAcGenero.getSelectedItem();
             String telefone = txtAcTelefone.getText();
             int idCliente = clienteCarregado.getIdCliente();
             Cliente novoCliente = new Cliente(idCliente,nome, email, cpf, dtEua, sexo,telefone);
            
             
             String logadouro = txtAcLogradouro.getText().toUpperCase();
             String cep = txtAcCep.getText();
             String numero = txtAcNumero.getText();
             String complemento = txtAcComplemento.getText().toUpperCase();
             String bairro = txtAcBairro.getText().toUpperCase();
             String cidade = txtAcCidade.getText().toUpperCase();
             String uf = (String) cboAcUF.getSelectedItem();
             int idEndereco = enderecoCarregado.getIdEndereco();
             
             Endereco novoEndereco = new Endereco(idEndereco,cep, logadouro, numero, complemento, bairro, cidade, uf);
              boolean retornoC = ClienteDAO.alterar(novoCliente, novoEndereco);
            if (retornoC == true) {

                JOptionPane.showMessageDialog(rootPane, "Foi salvo cliente:)");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não salvou o cliente :(");
            }
      }
    }//GEN-LAST:event_btnAcAtualizarActionPerformed

    public Date TraduzirData(String dtBr){
        String dia =  Character.toString(dtBr.charAt(0)) + Character.toString(dtBr.charAt(1));
        String mes = Character.toString(dtBr.charAt(3)) + Character.toString(dtBr.charAt(4));
        String ano = Character.toString(dtBr.charAt(6)) + Character.toString(dtBr.charAt(7)) +
                     Character.toString(dtBr.charAt(8)) + Character.toString(dtBr.charAt(9));
        Date data = null;
        if(Integer.parseInt(mes) > 12 || Integer.parseInt(mes) < 0){
               JOptionPane.showMessageDialog(rootPane, "Mês informado não existe");
               
        }
        else{
            String dtIso = ano+"-"+mes+"-"+dia;

            data = Date.valueOf(dtIso);

            
        }
        
        return data;
    }
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcAtualizar;
    private javax.swing.JButton btnAcCancelar;
    private javax.swing.JComboBox<String> cboAcGenero;
    private javax.swing.JComboBox<String> cboAcUF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAc;
    private javax.swing.JLabel lblAcBairro;
    private javax.swing.JLabel lblAcCep;
    private javax.swing.JLabel lblAcCidade;
    private javax.swing.JLabel lblAcComplemento;
    private javax.swing.JLabel lblAcCpf;
    private javax.swing.JLabel lblAcDtNascimento;
    private javax.swing.JLabel lblAcEmail;
    private javax.swing.JLabel lblAcGenero;
    private javax.swing.JLabel lblAcLogradouro;
    private javax.swing.JLabel lblAcNome;
    private javax.swing.JLabel lblAcNumero;
    private javax.swing.JLabel lblAcTelefone;
    private javax.swing.JLabel lblAcUf;
    private javax.swing.JPanel pnlAc;
    private javax.swing.JTextField txtAcBairro;
    private javax.swing.JFormattedTextField txtAcCep;
    private javax.swing.JTextField txtAcCidade;
    private javax.swing.JTextField txtAcComplemento;
    private javax.swing.JFormattedTextField txtAcDtNascimento;
    private javax.swing.JTextField txtAcEmail;
    private javax.swing.JTextField txtAcLogradouro;
    private javax.swing.JTextField txtAcNome;
    private javax.swing.JTextField txtAcNumero;
    private javax.swing.JFormattedTextField txtAcTelefone;
    private javax.swing.JFormattedTextField txtCdcCpf;
    // End of variables declaration//GEN-END:variables
}
