/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.pi.basepi.VIEW;

import java.text.SimpleDateFormat;
import projeto.pi.basepi.MODELS.Cliente;
import projeto.pi.basepi.MODELS.Endereco;

/**
 *
 * @author Athyla
 */
public class DetalhesCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public DetalhesCliente() {
        initComponents();
    }
    
    public DetalhesCliente(Cliente cliente, Endereco endereco) {
        initComponents();
        txtDcNome.setText(cliente.getNome());
        txtDcNome.enable(false);
        
        txtDcEmail.setText(cliente.getEmail());
        txtDcEmail.enable(false);
        
        txtDcCpf.setText(cliente.getCPF());
        txtDcCpf.enable(false);
        SimpleDateFormat dtBrasil = new SimpleDateFormat("dd/MM/yyyy");
        
        txtDcDtNascimento.setText(dtBrasil.format(cliente.getDataNascimento()));
        txtDcDtNascimento.enable(false);
        
        txtTelefone.setText(cliente.getTelefone());
        txtTelefone.enable(false);
        
        if(cliente.getGenero().equalsIgnoreCase("Masculino")){
            cboDcGenero.setSelectedIndex(0);
        }
        else if(cliente.getGenero().equalsIgnoreCase("Feminino")){
            cboDcGenero.setSelectedIndex(1);
        }
        else{
            cboDcGenero.setSelectedIndex(2);
            
        }
        
        txtDcLogradouro.setText(endereco.getLogradouro());
        txtDcLogradouro.enable(false);
        
        txtDcNumero.setText(endereco.getNumero());
        txtDcNumero.enable(false);
        
        txtDcCep.setText(endereco.getCep());
        txtDcCep.enable(false);
        
        txtDcBairro.setText(endereco.getBairro());
        txtDcBairro.enable(false);
        
        txtDcComplemento.setText(endereco.getComplemento());
        txtDcComplemento.enable(false);
        
        txtDcCidade.setText(endereco.getCidade());
        txtDcCidade.enable(false);
        
        cboDcUF.setSelectedItem(endereco.getUf());
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblDcNome = new javax.swing.JLabel();
        txtDcNome = new javax.swing.JTextField();
        lblDcEmail = new javax.swing.JLabel();
        txtDcEmail = new javax.swing.JTextField();
        lblDcDtNascimento = new javax.swing.JLabel();
        txtDcDtNascimento = new javax.swing.JFormattedTextField();
        lblDcGenero = new javax.swing.JLabel();
        cboDcGenero = new javax.swing.JComboBox<>();
        lblDcCpf = new javax.swing.JLabel();
        txtDcCpf = new javax.swing.JFormattedTextField();
        btnDcFechar = new javax.swing.JButton();
        lblDcDtNascimento1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDcLogradouro = new javax.swing.JLabel();
        txtDcLogradouro = new javax.swing.JTextField();
        lblDcNumero = new javax.swing.JLabel();
        txtDcNumero = new javax.swing.JTextField();
        lblDcCep = new javax.swing.JLabel();
        txtDcCep = new javax.swing.JFormattedTextField();
        lblDcBairro = new javax.swing.JLabel();
        txtDcBairro = new javax.swing.JTextField();
        lblDcComplemento = new javax.swing.JLabel();
        txtDcComplemento = new javax.swing.JTextField();
        lblDcCidade = new javax.swing.JLabel();
        txtDcCidade = new javax.swing.JTextField();
        lblDcUf = new javax.swing.JLabel();
        cboDcUF = new javax.swing.JComboBox<>();
        btnDcFechar2 = new javax.swing.JButton();
        pnlDc = new javax.swing.JPanel();
        lblDc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDcNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcNome.setText("Nome*:");

        lblDcEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcEmail.setText("E-mail*:");

        lblDcDtNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcDtNascimento.setText("Data de Nascimento*:");

        try {
            txtDcDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDcDtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDcDtNascimentoActionPerformed(evt);
            }
        });

        lblDcGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcGenero.setText("Gênero*:");

        cboDcGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Transgênero" }));
        cboDcGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDcGeneroActionPerformed(evt);
            }
        });

        lblDcCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcCpf.setText("CPF*:");

        try {
            txtDcCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnDcFechar.setText("Fechar");
        btnDcFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDcFecharActionPerformed(evt);
            }
        });

        lblDcDtNascimento1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcDtNascimento1.setText("Telefone*:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblDcNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDcNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDcDtNascimento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDcFechar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDcDtNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDcDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDcGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboDcGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDcEmail)
                            .addComponent(lblDcCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDcEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDcCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcNome)
                    .addComponent(txtDcNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcEmail)
                    .addComponent(txtDcEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcCpf)
                    .addComponent(txtDcCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcDtNascimento)
                    .addComponent(txtDcDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDcGenero)
                    .addComponent(cboDcGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcDtNascimento1)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDcFechar)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        lblDcLogradouro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcLogradouro.setText("Logradouro*:");

        lblDcNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcNumero.setText("Número*:");

        lblDcCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcCep.setText("CEP*:");

        try {
            txtDcCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDcBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcBairro.setText("Bairro*:");

        lblDcComplemento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcComplemento.setText("Complemento:");

        lblDcCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcCidade.setText("Cidade*:");

        lblDcUf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDcUf.setText("UF*:");

        cboDcUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "TO", " " }));
        cboDcUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDcUFActionPerformed(evt);
            }
        });

        btnDcFechar2.setText("Fechar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDcCidade)
                                .addGap(18, 18, 18)
                                .addComponent(txtDcCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDcUf)
                                .addGap(18, 18, 18)
                                .addComponent(cboDcUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDcLogradouro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDcLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDcNumero)
                                    .addComponent(lblDcBairro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtDcNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDcCep)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDcCep, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDcBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDcComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDcComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDcFechar2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcLogradouro)
                    .addComponent(txtDcLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcNumero)
                    .addComponent(txtDcNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDcCep)
                    .addComponent(txtDcCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcBairro)
                    .addComponent(txtDcBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcComplemento)
                    .addComponent(txtDcComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDcCidade)
                    .addComponent(txtDcCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDcUf)
                    .addComponent(cboDcUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnDcFechar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        pnlDc.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDc.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDc.setText("Detalhe Cliente ");

        javax.swing.GroupLayout pnlDcLayout = new javax.swing.GroupLayout(pnlDc);
        pnlDc.setLayout(pnlDcLayout);
        pnlDcLayout.setHorizontalGroup(
            pnlDcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );
        pnlDcLayout.setVerticalGroup(
            pnlDcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDc)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(pnlDc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlDc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboDcUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDcUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDcUFActionPerformed

    private void cboDcGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDcGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDcGeneroActionPerformed

    private void btnDcFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDcFecharActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_btnDcFecharActionPerformed

    private void txtDcDtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDcDtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDcDtNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDcFechar;
    private javax.swing.JButton btnDcFechar2;
    private javax.swing.JComboBox<String> cboDcGenero;
    private javax.swing.JComboBox<String> cboDcUF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDc;
    private javax.swing.JLabel lblDcBairro;
    private javax.swing.JLabel lblDcCep;
    private javax.swing.JLabel lblDcCidade;
    private javax.swing.JLabel lblDcComplemento;
    private javax.swing.JLabel lblDcCpf;
    private javax.swing.JLabel lblDcDtNascimento;
    private javax.swing.JLabel lblDcDtNascimento1;
    private javax.swing.JLabel lblDcEmail;
    private javax.swing.JLabel lblDcGenero;
    private javax.swing.JLabel lblDcLogradouro;
    private javax.swing.JLabel lblDcNome;
    private javax.swing.JLabel lblDcNumero;
    private javax.swing.JLabel lblDcUf;
    private javax.swing.JPanel pnlDc;
    private javax.swing.JTextField txtDcBairro;
    private javax.swing.JFormattedTextField txtDcCep;
    private javax.swing.JTextField txtDcCidade;
    private javax.swing.JTextField txtDcComplemento;
    private javax.swing.JFormattedTextField txtDcCpf;
    private javax.swing.JFormattedTextField txtDcDtNascimento;
    private javax.swing.JTextField txtDcEmail;
    private javax.swing.JTextField txtDcLogradouro;
    private javax.swing.JTextField txtDcNome;
    private javax.swing.JTextField txtDcNumero;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
